version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: meu_secure_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperSecurePass123! # رح نستخدمها للربط مع الـ C#
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data: